# theme: jekyll-theme-leap-day
# General Settings
title: Wesley Kirui | Data Science
email: kkiruiwesley@gmail.com
description: "My Data Science Journey"
baseurl: ""
url: ""

# Google Analytics
google_analytics : "G-DLXVJQKB9K"

# build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  # - jekyll-assets